---
- name: Hardening Network Configuration
  hosts: all
  become: yes
  tasks:
    - name: Disable IPv6 (if not required by policy)
      sysctl:
        name: "{{ item }}"
        value: '1'
        state: present
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6

    - name: Configure UFW to allow only Essential Ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - '22'
        - '80'
        - '443'

    - name: Enable Firewall
      ufw:
        state: enabled
